# Generated by Django 2.2 on 2019-12-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191207_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('product', 'cart', 'quantity')},
        ),
    ]
