# Generated by Django 2.2 on 2019-12-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191207_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivered',
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('BP', 'being processed'), ('BF', 'being formed'), ('ID', 'in delivery'), ('D', 'delivered')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
