# Generated by Django 2.2 on 2019-12-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191210_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('BP', 'being processed'), ('BF', 'being formed'), ('ID', 'in delivery'), ('D', 'delivered')], default='BP', max_length=2),
        ),
    ]
