# Generated by Django 2.2 on 2019-12-14 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191212_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_code', to='products.Cart'),
        ),
    ]
