# Generated by Django 2.2 on 2019-12-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191214_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('BP', 'обрабатывается'), ('BF', 'формируется'), ('ID', 'доставляется'), ('D', 'доставлен')], default='BP', max_length=2),
        ),
    ]
